stages:
  - lint
  - build
  - deploy

lint:
  image: 172.22.121.50/dockerhub/library/node:22-alpine
  stage: lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - node_modules/
  tags:
    - 'k8s_runner_report'
  script:
    - npm config set registry http://172.22.121.51:8081/repository/npm-public/
    - npm install -g pnpm
    - pnpm i --frozen-lockfile --registry=http://172.22.121.51:8081/repository/npm-public
    - pnpm run prettier-check
    - pnpm run lint

build:
  image:
    name: 172.22.121.50/gcr/kaniko-project/executor:v1.23.0-debug
    entrypoint: ['']
  stage: build
  tags:
    - 'k8s_runner_report'
  only:
    refs:
      - main
  cache:
    paths:
      - ./cache
  script:
    - echo "{\"auths\":{\"${KCI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${KCI_REGISTRY_USER}" "${KCI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/warmer
      --skip-tls-verify-pull
      --dockerfile "Dockerfile"
      --skip-tls-verify-registry 172.22.121.50
    - /kaniko/executor
      --skip-tls-verify
      --dockerfile "Dockerfile"
      --context ./
      --destination 172.22.121.50/reportgen/reportgen-frontend-react:$CI_PIPELINE_IID

deploy:
  image: 172.22.121.50/dockerio/bitnami/kubectl:1.23
  stage: deploy
  only:
    refs:
      - main
  tags:
    - 'k8s_runner_report'
  script:
    - sed -i "s/\$CI_PIPELINE_IID/${CI_PIPELINE_IID}/g" ./deployment.yaml
    - kubectl apply -f ./deployment.yaml
