apiVersion: apps/v1
kind: Deployment
metadata:
    name: reportgen-frontend-react
    labels:
        app: reportgen-frontend-react
spec:
    replicas: 1
    selector:
        matchLabels:
            app: reportgen-frontend-react
    template:
        metadata:
            labels:
                app: reportgen-frontend-react
        spec:
            containers:
                - name: reportgen-frontend-react-service
                  image: 172.22.121.50/reportgen/reportgen-frontend-react:$CI_PIPELINE_IID
                  ports:
                      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: reportgen-frontend-react-service
spec:
    type: NodePort
    selector:
        app: reportgen-frontend-react
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
