import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

import './globals.css'

import { ReactNode, useState } from 'react'
import Script from 'next/script'


import Header from './components/header'
import Sidebar from './components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '智能调研助手',

  description:
    'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  
  
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={inter.className}>
        {/* <Header /> */}
        <div className='flex'>
          <Sidebar ></Sidebar>
          {children}
        </div>


      </body>
    </html>
  )
}
